import pandas as pd
import json
from pathlib import Path


from ruler_decomposed_distillation import distill_musique
from ruler_hqa_sft_distill import distill_hotpot
from ruler_general_sft_distill import distill_squad
from sft_filter import *

def convert_parquet_to_json(parquet_file_path: str, json_file_path: str, sample_size: int = None, seed: int = 42):
    """
    Converts a Parquet file generated by the previous script into a JSON file.
    Renames the 'context' column to 'input'.

    Args:
        parquet_file_path (str): The path to the input Parquet file.
        json_file_path (str): The desired path for the output JSON file.
        sample_size (int): Number of random samples to select. If None, use all data.
        seed (int): Random seed for reproducibility.
    """
    # Load the Parquet file into a Pandas DataFrame
    df = pd.read_parquet(parquet_file_path)
    # print(len(df))
    # # Randomly sample if sample_size is specified
    if sample_size is not None and sample_size < len(df):
        df = df.sample(n=sample_size, random_state=seed)
        print(f"Randomly selected {sample_size} samples from {len(df)} total records (seed={seed})")

    # # Convert to records
    records = []
    for i, record in enumerate(df.to_dict(orient='records')):
        records.append({
            'context': record['context'],
            'input': record['prompt'][0]['content'],
            'answers': list(record['reward_model']['ground_truth']),
            'num_docs': record['extra_info']['num_docs'],
            'index': record['extra_info']['index'],
        })

    # Save the list of dictionaries to a JSON file
    Path(json_file_path).parent.mkdir(parents=True, exist_ok=True)
    with open(json_file_path, 'w', encoding='utf-8') as f:
        json.dump(records, f, ensure_ascii=False, indent=4)

    print(f"Successfully converted '{parquet_file_path}' to '{json_file_path}'.")
    print(f"Total records saved: {len(records)}")


import os

dataset_root = os.getenv("DATAROOT", "../../hotpotqa")
input_dir =  os.path.join(dataset_root,'train')
input_parquet_file = f'{dataset_root}/hotpotqa_train_32k.parquet'
output_json_file = f"{input_dir}/train_hotpotqa_32768.json"
n_sample = 3
# convert_parquet_to_json(input_parquet_file, output_json_file, sample_size=n_sample, seed=42)

save_dir = os.path.join(dataset_root,'distillation')
os.makedirs(save_dir, exist_ok=True)

hqa_path = f"{input_dir}/train_hotpotqa_32768.json"
hqa_out = f"{save_dir}/distilled_hotpotqa.jsonl"

sqd_path = f"{input_dir}/train_qa_1_32768.json"
sqd_out = f"{save_dir}/distilled_squad.jsonl"


msq_path = f"{input_dir}/train_qa_3_32768.json"
msq_out = f"{save_dir}/distilled_musique.jsonl"

# distill_hotpot(hqa_path,hqa_out,n_sample)
# distill_squad(sqd_path,sqd_out,n_sample)
# distill_musique(msq_path,msq_out,n_sample)
# msq_out_shorten = msq_out.replace(".jsonl","shorten_1436.jsonl")
from utils.filter_rewrite_musique import filter_by_len

input_file = [hqa_out,sqd_out,msq_out]

output_file = f"{save_dir}/sft_data.jsonl"

process_datasets_for_sft(
    input_jsonl_list=input_file,
    output_jsonl=output_file,
    filter_threshold=1.0,     # keep items with judge_em >= 1.0 (adjust as needed)
    score_key="judge_sub_em",     # or "judge_sub_em" if you prefer
    seed=42
)


# Validate output
validate_trl_format(output_file,60)


output_file_shorten = output_file.replace(".jsonl","shorten_1436.jsonl")
filter_by_len(output_file,  output_file_shorten)